version: '3.9'
services:
  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Asia/Seoul
    volumes:
      - n8n_data:/home/node/.n8n
  gateway:
    image: nginx:1.25
    ports: ["8080:80"]
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [nl-dsl, planner, policy-guard, manifest]
  nl-dsl:
    build: { context: ./services/nl-dsl }
    environment: [ "PORT=3001" ]
    ports: ["3001:3001"]
  planner:
    build: { context: ./services/planner }
    environment: [ "PORT=3002" ]
    ports: ["3002:3002"]
  policy-guard:
    build: { context: ./services/policy-guard }
    environment: [ "PORT=3003" ]
    ports: ["3003:3003"]
  manifest:
    build: { context: ./services/manifest }
    environment: [ "PORT=3004" ]
    ports: ["3004:3004"]
volumes:
  n8n_data: {}
