services:
  manifest:
    build:
      context: ./services/manifest
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - aga-net

  nl-dsl:
    build:
      context: ./services/nl-dsl
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - aga-net

  planner:
    build:
      context: ./services/planner
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - aga-net

  gateway:
    image: nginx:alpine
    depends_on:
      - manifest
      - nl-dsl
      - planner
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - aga-net

networks:
  aga-net:
    driver: bridge
